"""Curated skill keywords for data + AI engineer roles."""

SKILLS: list[str] = [
    "Python",
    "SQL",
    "Spark",
    "PySpark",
    "Databricks",
    "Snowflake",
    "dbt",
    "Airflow",
    "ADF",
    "AWS",
    "Azure",
    "GCP",
    "BigQuery",
    "Redshift",
    "S3",
    "Lambda",
    "Glue",
    "Kafka",
    "LangChain",
    "LangGraph",
    "RAG",
    "FastAPI",
    "Docker",
    "Kubernetes",
    "MLOps",
    "LLMOps",
    "embeddings",
    "vector database",
    "Chroma",
    "Pinecone",
    "FAISS",
    "OpenAI",
    "Hugging Face",
    "CI/CD",
    "Azure DevOps",
    "GitHub Actions",
    "Pandas",
    "NumPy",
    "Redis",
    "PostgreSQL",
    "Power BI",
    "DAX",
    ".NET",
    "C#",
    "Terraform",
    "Prometheus",
    "Grafana",
    "Streamlit",
    "Gradio",
    "OpenSearch",
    "Elasticsearch",
    "Delta Lake",
    "Parquet",
    "REST API",
    "GraphQL",
    "unittest",
    "pytest",
]
